name: Push Package to PyPi
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: ls
#       - run: python3 -m pip install build
#       - run: python3 -m pip install twine
#       - run: python3 -m build
#       - run: python3 -m twine upload -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASS }} dist/*